// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(workspace_ffiFFI)
import workspace_ffiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_workspace_ffi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_workspace_ffi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureWorkspaceFfiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles. 
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt64: FfiConverterPrimitive {
    typealias FfiType = Int64
    typealias SwiftType = Int64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int64, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}




public protocol WorkspaceServiceProtocol: AnyObject, Sendable {
    
    func createWorkspace(name: String) throws  -> String
    
    func listWorkspaceSummaries() throws  -> [WorkspaceSummary]
    
    func reconcileInterruptedSessions() throws 
    
    func updateWorkspaceNote(workspaceId: String, noteBody: String) throws 
    
    func workspaceDetail(workspaceId: String) throws  -> WorkspaceDetail
    
}
open class WorkspaceService: WorkspaceServiceProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_workspace_ffi_fn_clone_workspaceservice(self.handle, $0) }
    }
public convenience init(storePath: String)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeWorkspaceServiceError_lift) {
    uniffi_workspace_ffi_fn_constructor_workspaceservice_new(
        FfiConverterString.lower(storePath),$0
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_workspace_ffi_fn_free_workspaceservice(handle, $0) }
    }

    

    
open func createWorkspace(name: String)throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeWorkspaceServiceError_lift) {
    uniffi_workspace_ffi_fn_method_workspaceservice_create_workspace(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(name),$0
    )
})
}
    
open func listWorkspaceSummaries()throws  -> [WorkspaceSummary]  {
    return try  FfiConverterSequenceTypeWorkspaceSummary.lift(try rustCallWithError(FfiConverterTypeWorkspaceServiceError_lift) {
    uniffi_workspace_ffi_fn_method_workspaceservice_list_workspace_summaries(
            self.uniffiCloneHandle(),$0
    )
})
}
    
open func reconcileInterruptedSessions()throws   {try rustCallWithError(FfiConverterTypeWorkspaceServiceError_lift) {
    uniffi_workspace_ffi_fn_method_workspaceservice_reconcile_interrupted_sessions(
            self.uniffiCloneHandle(),$0
    )
}
}
    
open func updateWorkspaceNote(workspaceId: String, noteBody: String)throws   {try rustCallWithError(FfiConverterTypeWorkspaceServiceError_lift) {
    uniffi_workspace_ffi_fn_method_workspaceservice_update_workspace_note(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(workspaceId),
        FfiConverterString.lower(noteBody),$0
    )
}
}
    
open func workspaceDetail(workspaceId: String)throws  -> WorkspaceDetail  {
    return try  FfiConverterTypeWorkspaceDetail_lift(try rustCallWithError(FfiConverterTypeWorkspaceServiceError_lift) {
    uniffi_workspace_ffi_fn_method_workspaceservice_workspace_detail(
            self.uniffiCloneHandle(),
        FfiConverterString.lower(workspaceId),$0
    )
})
}
    

    
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWorkspaceService: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = WorkspaceService

    public static func lift(_ handle: UInt64) throws -> WorkspaceService {
        return WorkspaceService(unsafeFromHandle: handle)
    }

    public static func lower(_ value: WorkspaceService) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WorkspaceService {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: WorkspaceService, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceService_lift(_ handle: UInt64) throws -> WorkspaceService {
    return try FfiConverterTypeWorkspaceService.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceService_lower(_ value: WorkspaceService) -> UInt64 {
    return FfiConverterTypeWorkspaceService.lower(value)
}




public struct RestoreRecipe: Equatable, Hashable {
    public var launchCommand: String

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(launchCommand: String) {
        self.launchCommand = launchCommand
    }

    

    
}

#if compiler(>=6)
extension RestoreRecipe: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRestoreRecipe: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RestoreRecipe {
        return
            try RestoreRecipe(
                launchCommand: FfiConverterString.read(from: &buf)
        )
    }

    public static func write(_ value: RestoreRecipe, into buf: inout [UInt8]) {
        FfiConverterString.write(value.launchCommand, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRestoreRecipe_lift(_ buf: RustBuffer) throws -> RestoreRecipe {
    return try FfiConverterTypeRestoreRecipe.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRestoreRecipe_lower(_ value: RestoreRecipe) -> RustBuffer {
    return FfiConverterTypeRestoreRecipe.lower(value)
}


public struct TerminalGrid: Equatable, Hashable {
    public var cols: UInt16
    public var rows: UInt16
    public var lines: [String]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(cols: UInt16, rows: UInt16, lines: [String]) {
        self.cols = cols
        self.rows = rows
        self.lines = lines
    }

    

    
}

#if compiler(>=6)
extension TerminalGrid: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTerminalGrid: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TerminalGrid {
        return
            try TerminalGrid(
                cols: FfiConverterUInt16.read(from: &buf), 
                rows: FfiConverterUInt16.read(from: &buf), 
                lines: FfiConverterSequenceString.read(from: &buf)
        )
    }

    public static func write(_ value: TerminalGrid, into buf: inout [UInt8]) {
        FfiConverterUInt16.write(value.cols, into: &buf)
        FfiConverterUInt16.write(value.rows, into: &buf)
        FfiConverterSequenceString.write(value.lines, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTerminalGrid_lift(_ buf: RustBuffer) throws -> TerminalGrid {
    return try FfiConverterTypeTerminalGrid.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTerminalGrid_lower(_ value: TerminalGrid) -> RustBuffer {
    return FfiConverterTypeTerminalGrid.lower(value)
}


public struct WorkspaceClosedSessionSummary: Equatable, Hashable {
    public var id: String
    public var title: String
    public var transport: SessionTransport
    public var targetLabel: String
    public var lastCwd: String?
    public var closeReason: CloseReason
    public var snapshotPreview: TerminalGrid
    public var restoreRecipe: RestoreRecipe

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, title: String, transport: SessionTransport, targetLabel: String, lastCwd: String?, closeReason: CloseReason, snapshotPreview: TerminalGrid, restoreRecipe: RestoreRecipe) {
        self.id = id
        self.title = title
        self.transport = transport
        self.targetLabel = targetLabel
        self.lastCwd = lastCwd
        self.closeReason = closeReason
        self.snapshotPreview = snapshotPreview
        self.restoreRecipe = restoreRecipe
    }

    

    
}

#if compiler(>=6)
extension WorkspaceClosedSessionSummary: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWorkspaceClosedSessionSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WorkspaceClosedSessionSummary {
        return
            try WorkspaceClosedSessionSummary(
                id: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                transport: FfiConverterTypeSessionTransport.read(from: &buf), 
                targetLabel: FfiConverterString.read(from: &buf), 
                lastCwd: FfiConverterOptionString.read(from: &buf), 
                closeReason: FfiConverterTypeCloseReason.read(from: &buf), 
                snapshotPreview: FfiConverterTypeTerminalGrid.read(from: &buf), 
                restoreRecipe: FfiConverterTypeRestoreRecipe.read(from: &buf)
        )
    }

    public static func write(_ value: WorkspaceClosedSessionSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterTypeSessionTransport.write(value.transport, into: &buf)
        FfiConverterString.write(value.targetLabel, into: &buf)
        FfiConverterOptionString.write(value.lastCwd, into: &buf)
        FfiConverterTypeCloseReason.write(value.closeReason, into: &buf)
        FfiConverterTypeTerminalGrid.write(value.snapshotPreview, into: &buf)
        FfiConverterTypeRestoreRecipe.write(value.restoreRecipe, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceClosedSessionSummary_lift(_ buf: RustBuffer) throws -> WorkspaceClosedSessionSummary {
    return try FfiConverterTypeWorkspaceClosedSessionSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceClosedSessionSummary_lower(_ value: WorkspaceClosedSessionSummary) -> RustBuffer {
    return FfiConverterTypeWorkspaceClosedSessionSummary.lower(value)
}


public struct WorkspaceDetail: Equatable, Hashable {
    public var id: String
    public var name: String
    public var noteBody: String
    public var liveSessions: [WorkspaceSessionSummary]
    public var closedSessions: [WorkspaceClosedSessionSummary]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, noteBody: String, liveSessions: [WorkspaceSessionSummary], closedSessions: [WorkspaceClosedSessionSummary]) {
        self.id = id
        self.name = name
        self.noteBody = noteBody
        self.liveSessions = liveSessions
        self.closedSessions = closedSessions
    }

    

    
}

#if compiler(>=6)
extension WorkspaceDetail: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWorkspaceDetail: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WorkspaceDetail {
        return
            try WorkspaceDetail(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                noteBody: FfiConverterString.read(from: &buf), 
                liveSessions: FfiConverterSequenceTypeWorkspaceSessionSummary.read(from: &buf), 
                closedSessions: FfiConverterSequenceTypeWorkspaceClosedSessionSummary.read(from: &buf)
        )
    }

    public static func write(_ value: WorkspaceDetail, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterString.write(value.noteBody, into: &buf)
        FfiConverterSequenceTypeWorkspaceSessionSummary.write(value.liveSessions, into: &buf)
        FfiConverterSequenceTypeWorkspaceClosedSessionSummary.write(value.closedSessions, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceDetail_lift(_ buf: RustBuffer) throws -> WorkspaceDetail {
    return try FfiConverterTypeWorkspaceDetail.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceDetail_lower(_ value: WorkspaceDetail) -> RustBuffer {
    return FfiConverterTypeWorkspaceDetail.lower(value)
}


public struct WorkspaceSessionSummary: Equatable, Hashable {
    public var id: String
    public var title: String
    public var transport: SessionTransport
    public var targetLabel: String
    public var lastCwd: String?
    public var closeReason: CloseReason

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, title: String, transport: SessionTransport, targetLabel: String, lastCwd: String?, closeReason: CloseReason) {
        self.id = id
        self.title = title
        self.transport = transport
        self.targetLabel = targetLabel
        self.lastCwd = lastCwd
        self.closeReason = closeReason
    }

    

    
}

#if compiler(>=6)
extension WorkspaceSessionSummary: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWorkspaceSessionSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WorkspaceSessionSummary {
        return
            try WorkspaceSessionSummary(
                id: FfiConverterString.read(from: &buf), 
                title: FfiConverterString.read(from: &buf), 
                transport: FfiConverterTypeSessionTransport.read(from: &buf), 
                targetLabel: FfiConverterString.read(from: &buf), 
                lastCwd: FfiConverterOptionString.read(from: &buf), 
                closeReason: FfiConverterTypeCloseReason.read(from: &buf)
        )
    }

    public static func write(_ value: WorkspaceSessionSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.title, into: &buf)
        FfiConverterTypeSessionTransport.write(value.transport, into: &buf)
        FfiConverterString.write(value.targetLabel, into: &buf)
        FfiConverterOptionString.write(value.lastCwd, into: &buf)
        FfiConverterTypeCloseReason.write(value.closeReason, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceSessionSummary_lift(_ buf: RustBuffer) throws -> WorkspaceSessionSummary {
    return try FfiConverterTypeWorkspaceSessionSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceSessionSummary_lower(_ value: WorkspaceSessionSummary) -> RustBuffer {
    return FfiConverterTypeWorkspaceSessionSummary.lower(value)
}


public struct WorkspaceSummary: Equatable, Hashable {
    public var id: String
    public var name: String
    public var liveSessions: Int64
    public var recentlyClosedSessions: Int64
    public var hasInterruptedSessions: Bool
    public var updatedAt: Int64

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(id: String, name: String, liveSessions: Int64, recentlyClosedSessions: Int64, hasInterruptedSessions: Bool, updatedAt: Int64) {
        self.id = id
        self.name = name
        self.liveSessions = liveSessions
        self.recentlyClosedSessions = recentlyClosedSessions
        self.hasInterruptedSessions = hasInterruptedSessions
        self.updatedAt = updatedAt
    }

    

    
}

#if compiler(>=6)
extension WorkspaceSummary: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWorkspaceSummary: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WorkspaceSummary {
        return
            try WorkspaceSummary(
                id: FfiConverterString.read(from: &buf), 
                name: FfiConverterString.read(from: &buf), 
                liveSessions: FfiConverterInt64.read(from: &buf), 
                recentlyClosedSessions: FfiConverterInt64.read(from: &buf), 
                hasInterruptedSessions: FfiConverterBool.read(from: &buf), 
                updatedAt: FfiConverterInt64.read(from: &buf)
        )
    }

    public static func write(_ value: WorkspaceSummary, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterString.write(value.name, into: &buf)
        FfiConverterInt64.write(value.liveSessions, into: &buf)
        FfiConverterInt64.write(value.recentlyClosedSessions, into: &buf)
        FfiConverterBool.write(value.hasInterruptedSessions, into: &buf)
        FfiConverterInt64.write(value.updatedAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceSummary_lift(_ buf: RustBuffer) throws -> WorkspaceSummary {
    return try FfiConverterTypeWorkspaceSummary.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceSummary_lower(_ value: WorkspaceSummary) -> RustBuffer {
    return FfiConverterTypeWorkspaceSummary.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum CloseReason: Equatable, Hashable {
    
    case userClosed
    case processExited
    case sshDisconnected
    case appCrashed
    case hostQuit





}

#if compiler(>=6)
extension CloseReason: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeCloseReason: FfiConverterRustBuffer {
    typealias SwiftType = CloseReason

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> CloseReason {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .userClosed
        
        case 2: return .processExited
        
        case 3: return .sshDisconnected
        
        case 4: return .appCrashed
        
        case 5: return .hostQuit
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: CloseReason, into buf: inout [UInt8]) {
        switch value {
        
        
        case .userClosed:
            writeInt(&buf, Int32(1))
        
        
        case .processExited:
            writeInt(&buf, Int32(2))
        
        
        case .sshDisconnected:
            writeInt(&buf, Int32(3))
        
        
        case .appCrashed:
            writeInt(&buf, Int32(4))
        
        
        case .hostQuit:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCloseReason_lift(_ buf: RustBuffer) throws -> CloseReason {
    return try FfiConverterTypeCloseReason.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeCloseReason_lower(_ value: CloseReason) -> RustBuffer {
    return FfiConverterTypeCloseReason.lower(value)
}


// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.

public enum SessionTransport: Equatable, Hashable {
    
    case local
    case ssh





}

#if compiler(>=6)
extension SessionTransport: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeSessionTransport: FfiConverterRustBuffer {
    typealias SwiftType = SessionTransport

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SessionTransport {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .local
        
        case 2: return .ssh
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: SessionTransport, into buf: inout [UInt8]) {
        switch value {
        
        
        case .local:
            writeInt(&buf, Int32(1))
        
        
        case .ssh:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionTransport_lift(_ buf: RustBuffer) throws -> SessionTransport {
    return try FfiConverterTypeSessionTransport.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeSessionTransport_lower(_ value: SessionTransport) -> RustBuffer {
    return FfiConverterTypeSessionTransport.lower(value)
}



public enum WorkspaceServiceError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {

    
    
    case OpenStoreFailed(message: String)
    
    case CreateWorkspaceFailed(message: String)
    
    case UpdateWorkspaceNoteFailed(message: String)
    
    case WorkspaceDetailFailed(message: String)
    
    case PoisonedState(message: String)
    
    case ListWorkspacesFailed(message: String)
    
    case ReconcileInterruptedFailed(message: String)
    

    

    

    
    public var errorDescription: String? {
        String(reflecting: self)
    }
    
}

#if compiler(>=6)
extension WorkspaceServiceError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeWorkspaceServiceError: FfiConverterRustBuffer {
    typealias SwiftType = WorkspaceServiceError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> WorkspaceServiceError {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        

        
        case 1: return .OpenStoreFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 2: return .CreateWorkspaceFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 3: return .UpdateWorkspaceNoteFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 4: return .WorkspaceDetailFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 5: return .PoisonedState(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 6: return .ListWorkspacesFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        
        case 7: return .ReconcileInterruptedFailed(
            message: try FfiConverterString.read(from: &buf)
        )
        

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: WorkspaceServiceError, into buf: inout [UInt8]) {
        switch value {

        

        
        case .OpenStoreFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(1))
        case .CreateWorkspaceFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(2))
        case .UpdateWorkspaceNoteFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(3))
        case .WorkspaceDetailFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(4))
        case .PoisonedState(_ /* message is ignored*/):
            writeInt(&buf, Int32(5))
        case .ListWorkspacesFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(6))
        case .ReconcileInterruptedFailed(_ /* message is ignored*/):
            writeInt(&buf, Int32(7))

        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceServiceError_lift(_ buf: RustBuffer) throws -> WorkspaceServiceError {
    return try FfiConverterTypeWorkspaceServiceError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeWorkspaceServiceError_lower(_ value: WorkspaceServiceError) -> RustBuffer {
    return FfiConverterTypeWorkspaceServiceError.lower(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeWorkspaceClosedSessionSummary: FfiConverterRustBuffer {
    typealias SwiftType = [WorkspaceClosedSessionSummary]

    public static func write(_ value: [WorkspaceClosedSessionSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeWorkspaceClosedSessionSummary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [WorkspaceClosedSessionSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [WorkspaceClosedSessionSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeWorkspaceClosedSessionSummary.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeWorkspaceSessionSummary: FfiConverterRustBuffer {
    typealias SwiftType = [WorkspaceSessionSummary]

    public static func write(_ value: [WorkspaceSessionSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeWorkspaceSessionSummary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [WorkspaceSessionSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [WorkspaceSessionSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeWorkspaceSessionSummary.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeWorkspaceSummary: FfiConverterRustBuffer {
    typealias SwiftType = [WorkspaceSummary]

    public static func write(_ value: [WorkspaceSummary], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeWorkspaceSummary.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [WorkspaceSummary] {
        let len: Int32 = try readInt(&buf)
        var seq = [WorkspaceSummary]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeWorkspaceSummary.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_workspace_ffi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_workspace_ffi_checksum_method_workspaceservice_create_workspace() != 24040) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_workspace_ffi_checksum_method_workspaceservice_list_workspace_summaries() != 3972) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_workspace_ffi_checksum_method_workspaceservice_reconcile_interrupted_sessions() != 53886) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_workspace_ffi_checksum_method_workspaceservice_update_workspace_note() != 7326) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_workspace_ffi_checksum_method_workspaceservice_workspace_detail() != 942) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_workspace_ffi_checksum_constructor_workspaceservice_new() != 42942) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureWorkspaceFfiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all